config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'

  # get '/home',  to: 'static_pages#home'
  get '/help', to: 'static_pages#help' # , as: 'helf'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # GET, POST, PATCH, DELETE: Basic HTTP operations between Client & Server,
  # & fundamental of REST API architectures
  # For details on the DSL available within this file see:
  # http://guides.rubyonrails.org/routing.html
  # root 'application#test0'
  # For list of all routes in an application $ rails routes
end

app/models/application_record.rb
# frozen_string_literal: true

# The Overall ActiveRecord class for the entire Application
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

# The Class for the User model
class User < ApplicationRecord
  # validates (:name, presence: true)
  before_save { email.downcase! } # { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true # { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# The overall Controler for the entire application
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  def test0
    render html:
    "If you're reading this, application#test0 was created & routed correctly"
  end
end

#   $ rails generate controller StaticPages home help
#   $ rails destroy  controller StaticPages home help
#   Undoes the controller
#
#   $ rails generate model User name:string email:string
#   $ rails destroy model User
#   Undoes the model
#
#   $ rails db:migrate
#   Changes the state of the database to support the current models & etc.
#   $ rails db:rollback
#   Undoes one db:migrate
#   $ rails db:migrate VERSION=0
#   Undoes all db:migrate (s), or reverts to the db VERSION # for #>0

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# The Rest controller for the Sessions resource
class SessionsController < ApplicationController
  def new
    @title = 'Login'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy; end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# The Rest controller for the Static Pages resource
class StaticPagesController < ApplicationController
  def home
    @title = 'Home'
  end

  def help
    @title = 'Help'
  end

  def about
    @title = 'About'
  end

  def contact
    @title = 'Contact'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# The Rest controller for the Users resource
class UsersController < ApplicationController
  def new
    @title = 'Signup'
    @user = User.new
    # debugger
  end

  def create
    # debugger
    # @user = User.new(params[:user])
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user # user_url(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
    # debugger
    # Really flippin' useful! (Ctrl+d to exit)
  end

  private

  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper methods for application_controller
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.nil?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# Helper methods for sessions_controller
module SessionsHelper
  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

# Helper methods for static_pages_controller
module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Helper methods for users_controller
module UsersHelper
  # Returns the Gravatar associate with the user.email:string
  def gravatar_for(user, size: 80)
    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,
              alt: user.name,
              class: 'gravatar',
              id: 'round_corners_gravatar')
  end
end

app/views/layouts/OLDapplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Contact", contact_path%></li>
      <li><a href="http://news.railstutorial.org/">News</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>
  <%= full_title(@title) %>
  </title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <%= render 'layouts/shim'%>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo"%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <%= render 'layouts/head'%>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <!--
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        -->
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1 id="sample_header_about">About ;)</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:example, "Contact ") %>
<h1 id="sample_header_contact"> <%= yield(:example) %>&#x1F4DE;</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
  Or HMUP @ +1-202-555-6969 &#x1F48B;&#x1F48B;&#x1F48B;
</p>

app/views/static_pages/help.html.erb
<h1 id="sample_header_help">HELP!!!</h1>
<p id="p1">
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help" id="link">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book" id="link"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 id="sample_header_home">Welcome to the Sample App of Looooove!!!!!!!</h1>

  <h2 id="p1">
    This is the home page for the 
    <a href="https://www.railstutorial.org/" id="link">Ruby on Rails Tutorial<a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary"%>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %>
<%= link_to image_tag("kwitten.png", alt: "Cute little kitten", id: "round_corners_nyan"), 'http://www.nyan.cat/' %>

app/views/users/new.html.erb
<h1>^^^Sign Up^^^</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my Account!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(@user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for(@user, size: 80)  %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<!--
<%= @user.name %> | <%= @user.email %> | <%= @user.created_at %> | <%= @user.updated_at %>
<p>
<%= Time.now %>
-->